DefaultContentLanguage = "en"
title = "ayushe.com"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
publishDir = "public"
enableEmoji = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = ""
  mainSections = ["post","posts"]
  logo = "images/ayushe_img.jpeg" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Ayushe Nagpal"
  website = "ayushe.com"
  email = "ayushenagpal@gmail.com"
  # facebook = "username"
  github = "ayushen"
  # gitlab = "username"
  # bitbucket = "username"
  # twitter = "username"
  # reddit = "username"
  linkedin = "ayushe-nagpal-34101a158"
  # xing = "username"
  # stackoverflow = "users/XXXXXXX/username"
  # snapchat = "username"
  instagram = "ayushe.nagpal"
  # youtube = "user/username" # or channel/channelname
  # soundcloud = "username"
  # spotify = "username"
  # bandcamp = "username"
  # itchio = "username"
  # vk = "username"
  # paypal = "username"
  # telegram = "username"
  # 500px = "username"
  # codepen = "username"
  # mastodon = "url"
  # kaggle = "username"
  # weibo = "username"
  # slack = "username"

[[menu.main]]
    name = "Home"
    url = ""
    weight = 1

[[menu.main]]
    name = "Blog"
    url = "blog"
    weight = 2

[[menu.main]]
    identifier = "art"
	url = "page/art"
    name = "Art"
    weight = 3

[[menu.main]]
    identifier = "projects"
    name = "Projects"
	url = "page/projects"
    weight = 4

[[menu.main]]
	parent = "projects"
	identifier = "cs"
	name = "CS"
	url = "page/csprojects"
	weight = 1

[[menu.main]]
	parent = "projects"
	identifier = "misc"
	name = "Miscellaneous"
	url = "page/misc"
	weight = 2

[[menu.main]]
    identifier = "media"
    name = "Media"
	url = "page/media"
    weight = 5

